---
title: "Quarto Practice"
format: html
execute:
  warning: false
---

suppressing warnings and messages JUST for this code chunk

```{r}
#| warning: false
#| message: false
library(tidyverse)
```

running code, but not showing code or output

```{r}
#| include: false #must have space between | and words!!
#return the first 6 lines of star wars data
head(starwars)
#return the dimensions of the star ward data
dim(starwars)
```

showing output, but not code.

```{r}
#| warning: false
#| echo: false
ggplot(data = starwars, aes(x = height,
                            y = mass, 
                            color = mass))+
  geom_point()+
  labs(x="Height (cm)",
       y="Mass (kg)")
```

show only code and output.

```{r}
#| warning: false
#| fig-cap: "caption text"
#| fig-alt: "figure alt text"
ggplot(data = starwars, aes(x = height))+
  geom_histogram(color = "red", fill = "blue")
```

Find summary stats for star wars characters

```{r}
sw_height_mean <- mean(starwars$height, na.rm=T)
sw_height_median <- median(starwars$height, na.rm=T)
sw_height_var <- var(starwars$height, na.rm=T)
sw_height_sd <- sd(starwars$height, na.rm=T)
```

The mean height of the characters in Star Wars is `r round(sw_height_mean,1)` centimeters.
